feat: update public table
teamsela/sela-webapp pull request #26
Opened 2024-07-23 22:58 UTC by apphiaWang

In this PR:
- add the link to the view study page in the study name
- fix search studies, users can search by study name or passage
- update styling, remove the bottom passage info in the study name cell, reduce padding-y of the owner cell

Todo this week:
- Make public page accessible to visitors (unsigned-in users)

2024-07-24 04:24 UTC, teamsela requested changes
Instead of filtering a copy of returned studies from xata, can you use the phrase search API provided by xata?
https://xata.io/docs/sdk/search

Also, I notice that the query won't work if I type too fast. After entering a few characters, it doesn't focus on the text input. While you're at it, can you fix the search bar of "Recent" page and add pagination? You can find out how to do pagination here:
https://nextjs.org/learn/dashboard-app/adding-search-and-pagination

2024-07-29 02:32 UTC, apphiaWang commented on src/components/Tables/Public.tsx
Now I show this line if no records are searched in our db. May need to check with Toby.

2024-07-29 02:32 UTC, apphiaWang commented on src/components/Tables/Public.tsx
> +            <h2 className="text-xl"> Oops, we have nothing like that in our database...</h2>
Now I show this message if no public study is searched. May need to check with Toby.

2024-07-29 19:54 UTC, teamsela commented on src/components/Tables/Public.tsx
> +  const PAGINATION_SIZE = 5;
Can we set it to 10 instead of?

2024-07-29 19:55 UTC, teamsela requested changes
Can we also apply pagination to Recent page as well?

2024-08-03 04:21 UTC, merged